// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum CastApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct CastMediaRequest: Hashable, CustomStringConvertible {
  var url: String
  var title: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CastMediaRequest? {
    let url = pigeonVar_list[0] as! String
    let title = pigeonVar_list[1] as! String

    return CastMediaRequest(
      url: url,
      title: title
    )
  }
  func toList() -> [Any?] {
    return [
      url,
      title,
    ]
  }
  static func == (lhs: CastMediaRequest, rhs: CastMediaRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return CastApiPigeonInternal.deepEquals(lhs.url, rhs.url) && CastApiPigeonInternal.deepEquals(lhs.title, rhs.title)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CastMediaRequest")
    CastApiPigeonInternal.deepHash(value: url, hasher: &hasher)
    CastApiPigeonInternal.deepHash(value: title, hasher: &hasher)
  }

  public var description: String {
    return "CastMediaRequest(url: \(String(describing: url)), title: \(String(describing: title)))"
  }
}

private class CastApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return CastMediaRequest.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class CastApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CastMediaRequest {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class CastApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return CastApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return CastApiPigeonCodecWriter(data: data)
  }
}

class CastApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = CastApiPigeonCodec(readerWriter: CastApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ChromecastHostApi {
  func initializeCast() throws
  func isConnected() throws -> Bool
  func showCastDialog() throws
  func playMedia(request: CastMediaRequest) throws
  func stopMedia() throws
  func disconnectDevice() throws
  func pauseMedia() throws
  func resumeMedia() throws
  func seekMedia(positionInSeconds: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ChromecastHostApiSetup {
  static var codec: FlutterStandardMessageCodec { CastApiPigeonCodec.shared }
  /// Sets up an instance of `ChromecastHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ChromecastHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeCastChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.easy_chromecast_plugin.ChromecastHostApi.initializeCast\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeCastChannel.setMessageHandler { _, reply in
        do {
          try api.initializeCast()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeCastChannel.setMessageHandler(nil)
    }
    let isConnectedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.easy_chromecast_plugin.ChromecastHostApi.isConnected\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isConnectedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isConnected()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isConnectedChannel.setMessageHandler(nil)
    }
    let showCastDialogChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.easy_chromecast_plugin.ChromecastHostApi.showCastDialog\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showCastDialogChannel.setMessageHandler { _, reply in
        do {
          try api.showCastDialog()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showCastDialogChannel.setMessageHandler(nil)
    }
    let playMediaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.easy_chromecast_plugin.ChromecastHostApi.playMedia\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playMediaChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! CastMediaRequest
        do {
          try api.playMedia(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      playMediaChannel.setMessageHandler(nil)
    }
    let stopMediaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.easy_chromecast_plugin.ChromecastHostApi.stopMedia\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopMediaChannel.setMessageHandler { _, reply in
        do {
          try api.stopMedia()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopMediaChannel.setMessageHandler(nil)
    }
    let disconnectDeviceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.easy_chromecast_plugin.ChromecastHostApi.disconnectDevice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectDeviceChannel.setMessageHandler { _, reply in
        do {
          try api.disconnectDevice()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disconnectDeviceChannel.setMessageHandler(nil)
    }
    let pauseMediaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.easy_chromecast_plugin.ChromecastHostApi.pauseMedia\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseMediaChannel.setMessageHandler { _, reply in
        do {
          try api.pauseMedia()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pauseMediaChannel.setMessageHandler(nil)
    }
    let resumeMediaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.easy_chromecast_plugin.ChromecastHostApi.resumeMedia\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resumeMediaChannel.setMessageHandler { _, reply in
        do {
          try api.resumeMedia()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      resumeMediaChannel.setMessageHandler(nil)
    }
    let seekMediaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.easy_chromecast_plugin.ChromecastHostApi.seekMedia\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      seekMediaChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let positionInSecondsArg = args[0] as! Int64
        do {
          try api.seekMedia(positionInSeconds: positionInSecondsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      seekMediaChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol ChromecastFlutterApiProtocol {
  func onConnectionStatusChanged(isConnected isConnectedArg: Bool) async throws
}
class ChromecastFlutterApi: ChromecastFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: CastApiPigeonCodec {
    return CastApiPigeonCodec.shared
  }
  func onConnectionStatusChanged(isConnected isConnectedArg: Bool) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.easy_chromecast_plugin.ChromecastFlutterApi.onConnectionStatusChanged\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([isConnectedArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
