// Autogenerated from Pigeon (v21.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct CastMediaRequest {
  var url: String
  var title: String



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CastMediaRequest? {
    let url = pigeonVar_list[0] as! String
    let title = pigeonVar_list[1] as! String

    return CastMediaRequest(
      url: url,
      title: title
    )
  }
  func toList() -> [Any?] {
    return [
      url,
      title,
    ]
  }
}

private class CastApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return CastMediaRequest.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class CastApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CastMediaRequest {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class CastApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return CastApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return CastApiPigeonCodecWriter(data: data)
  }
}

class CastApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = CastApiPigeonCodec(readerWriter: CastApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ChromecastHostApi {
  func initializeCast() throws
  func isConnected() throws -> Bool
  func showCastDialog() throws
  func playMedia(request: CastMediaRequest) throws
  func stopMedia() throws
  func pauseMedia() throws
  func resumeMedia() throws
  func seekMedia(positionInSeconds: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ChromecastHostApiSetup {
  static var codec: FlutterStandardMessageCodec { CastApiPigeonCodec.shared }
  /// Sets up an instance of `ChromecastHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ChromecastHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeCastChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.easy_chromecast_plugin.ChromecastHostApi.initializeCast\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeCastChannel.setMessageHandler { _, reply in
        do {
          try api.initializeCast()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeCastChannel.setMessageHandler(nil)
    }
    let isConnectedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.easy_chromecast_plugin.ChromecastHostApi.isConnected\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isConnectedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isConnected()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isConnectedChannel.setMessageHandler(nil)
    }
    let showCastDialogChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.easy_chromecast_plugin.ChromecastHostApi.showCastDialog\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showCastDialogChannel.setMessageHandler { _, reply in
        do {
          try api.showCastDialog()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showCastDialogChannel.setMessageHandler(nil)
    }
    let playMediaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.easy_chromecast_plugin.ChromecastHostApi.playMedia\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playMediaChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! CastMediaRequest
        do {
          try api.playMedia(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      playMediaChannel.setMessageHandler(nil)
    }
    let stopMediaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.easy_chromecast_plugin.ChromecastHostApi.stopMedia\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopMediaChannel.setMessageHandler { _, reply in
        do {
          try api.stopMedia()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopMediaChannel.setMessageHandler(nil)
    }
    let pauseMediaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.easy_chromecast_plugin.ChromecastHostApi.pauseMedia\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseMediaChannel.setMessageHandler { _, reply in
        do {
          try api.pauseMedia()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pauseMediaChannel.setMessageHandler(nil)
    }
    let resumeMediaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.easy_chromecast_plugin.ChromecastHostApi.resumeMedia\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resumeMediaChannel.setMessageHandler { _, reply in
        do {
          try api.resumeMedia()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      resumeMediaChannel.setMessageHandler(nil)
    }
    let seekMediaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.easy_chromecast_plugin.ChromecastHostApi.seekMedia\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      seekMediaChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let positionInSecondsArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        do {
          try api.seekMedia(positionInSeconds: positionInSecondsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      seekMediaChannel.setMessageHandler(nil)
    }
  }
}
